---
title: "Hedonic_House_Prisce_M"
author: "Sognefest & Jones (2023)"
format: html
format: pdf
abstract: "The Hedonic Houseprice model with maps....."
editor: visual
bibliography: [.bib]
output-file: Assignment1.qmd
page-layout: full
number-sections: true
papersize: a4
---

```{r setup, include=FALSE}

library(Jmisc)
library(sf)
library(urbnmapr)
library(tidyverse)
library(ggplot2)
library(sp)
library(spdep)
library(spatialreg)
library(spData)
library(huxtable)
library(knitr)
```

```{r}
#opg1
kc_house_data <- read.csv("./Data/kc_house_data.csv")
kc_house_data$date <- lubridate::ymd_hms(kc_house_data$date) 

#lager datoobjekt

kc_house_data <- kc_house_data %>%
  mutate(year = year(date),
         month = month(date),
         day = day(date)) %>% #nye variabler for date, month, year
  arrange(desc(date)) %>% ##sortere datasett basert på dato
  distinct(id, .keep_all = TRUE) #behold bare siste salg
kc_house_data_sf <- st_as_sf(kc_house_data, coords = c("long", "lat"), crs = 4326) #Bruk st_as_sf() til å konvertere house data til et sf objekt vha. long lat og sett til geografisk projeksjon, dvs EPSG:4326.
kc_house_data_sf <- st_transform(kc_house_data_sf, 2926) 

#endre til EPSG:2926
```
